spring:
  datasource:
    url: jdbc:mysql://39.108.54.165:3307/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 39.108.54.165 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.tulingxueyuan: debug

aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4GHWCM5LdNoiLy35mBog # 访问身份验证中用到用户标识
    accessKeySecret: Vytl0LAIKGmiWATIuuwevN3LjzQs9S # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: tulingmall-xushu # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    #callback:  # 文件上传成功后的回调地址
    dir:
      prefix: tulingmall/images/ # 上传文件夹路径前缀
